version: 2

checks:
  identical-code:
    config:
      threshold: 25
  similar-code:
    config:
      threshold: 65

plugins:
  duplication:
    enabled: true
    debug: true
    config:
      languages:
        - javascript
        - typescript
  fixme:
    enabled: true
  eslint:
    enabled: true
    config:
      config: .eslintrc
      extensions:
        - .ts
        - .tsx
    channel: "eslint-7"

ratings:
  paths:
    - 'src/**'

exclude_patterns:
  - 'node_modules/'
  - 'coverage/'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
  - '**/*.stories.ts'
  - '**/*.stories.tsx'
  - 'build/'
  - '.vscode'
  - 'dist'
